google-sa: |
    ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZGF0YWZvbGQi
    example only
    ...
    example only
    ICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K
secrets:
    installMePassword: replace-this-with-your-secret
    mail:
        server: email-smtp.us-west-2.amazonaws.com
        defaultSender: noreply@acme.com
global:
    operator:
        allowRollback: false
        releaseChannel: stable
        backupCronSchedule: 0 1 * * *
        maintenanceWindow: ""
