global:
  datadog:
    env: prod
    install: false
  operator:
    allowRollback: false
    releaseChannel: stable
    backupCronSchedule: 0 1 * * *
    maintenanceWindow: ""
postgres:
  install: false
worker:
  resources:
    limits:
      memory: 8000Mi
    requests:
      memory: 8000Mi
worker-catalog:
  resources:
    limits:
      memory: 19000Mi
    requests:
      memory: 19000Mi